---
- hosts: all
  become: true
  
  tasks:
    - name: Add user to wheel group (RHEL/CentOS)
      command: > 
        usermod -aG wheel testuser
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Add user to sudo group (Debian/Ubuntu)
      command: >
        usermod -aG sudo testuser
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'