---
- hosts: all
  become: true
  
  tasks:
    - name: Remove user from wheel group (RHEL/CentOS)
      command: > 
        gpasswd -d testuser wheel
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Remove user from sudo group (Debian/Ubuntu)
      command: >
        deluser testuser sudo
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'